# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc_client_impl.proto.get_cpu_system_usage_pb2 as get__cpu__system__usage__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_cpu_system_usage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetCpuSystemUsageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCpuSystemUsage = channel.unary_unary(
                '/cpu_system_usage.GetCpuSystemUsageService/GetCpuSystemUsage',
                request_serializer=get__cpu__system__usage__pb2.GetCpuSystemUsageRequest.SerializeToString,
                response_deserializer=get__cpu__system__usage__pb2.GetCpuSystemUsageResponse.FromString,
                _registered_method=True)


class GetCpuSystemUsageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCpuSystemUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetCpuSystemUsageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCpuSystemUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuSystemUsage,
                    request_deserializer=get__cpu__system__usage__pb2.GetCpuSystemUsageRequest.FromString,
                    response_serializer=get__cpu__system__usage__pb2.GetCpuSystemUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cpu_system_usage.GetCpuSystemUsageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cpu_system_usage.GetCpuSystemUsageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetCpuSystemUsageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCpuSystemUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cpu_system_usage.GetCpuSystemUsageService/GetCpuSystemUsage',
            get__cpu__system__usage__pb2.GetCpuSystemUsageRequest.SerializeToString,
            get__cpu__system__usage__pb2.GetCpuSystemUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
