# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_cpu_system_usage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'get_cpu_system_usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aget_cpu_system_usage.proto\x12\x10\x63pu_system_usage\">\n\x18GetCpuSystemUsageRequest\x12\x11\n\tdate_from\x18\x01 \x01(\x03\x12\x0f\n\x07\x64\x61te_to\x18\x02 \x01(\x03\"P\n\x08\x43puUsage\x12\x0b\n\x03\x63pu\x18\x01 \x01(\t\x12\x11\n\tavg_usage\x18\x02 \x01(\x01\x12\x11\n\tmax_usage\x18\x03 \x01(\x01\x12\x11\n\tmin_usage\x18\x04 \x01(\x01\"G\n\x19GetCpuSystemUsageResponse\x12*\n\x06usages\x18\x01 \x03(\x0b\x32\x1a.cpu_system_usage.CpuUsage2\x88\x01\n\x18GetCpuSystemUsageService\x12l\n\x11GetCpuSystemUsage\x12*.cpu_system_usage.GetCpuSystemUsageRequest\x1a+.cpu_system_usage.GetCpuSystemUsageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_cpu_system_usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCPUSYSTEMUSAGEREQUEST']._serialized_start=48
  _globals['_GETCPUSYSTEMUSAGEREQUEST']._serialized_end=110
  _globals['_CPUUSAGE']._serialized_start=112
  _globals['_CPUUSAGE']._serialized_end=192
  _globals['_GETCPUSYSTEMUSAGERESPONSE']._serialized_start=194
  _globals['_GETCPUSYSTEMUSAGERESPONSE']._serialized_end=265
  _globals['_GETCPUSYSTEMUSAGESERVICE']._serialized_start=268
  _globals['_GETCPUSYSTEMUSAGESERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
